#
# RUN by:
# cp Dockerfile-Ubuntu-Container Dockerfile
# sudo docker build -t generate-subtitles .
# 
FROM ubuntu:22.04

MAINTAINER Hoan&lt;phamduyhoan95@gmail.com&gt;

RUN apt-get -y update && apt-get -y upgrade
RUN apt-get install -y nodejs
RUN apt-get install -y npm

ADD . / generate-subtitles/
RUN (cd generate-subtitles/; npm install;)
CMD (cd generate-subtitles/; npm start;)

# ENTRYPOINT [ "/bin/bash" ]

EXPOSE 3000