/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-southeast-1",
    "aws_appsync_graphqlEndpoint": "https://zrlu677xbfcllmsriw5vb66zam.appsync-api.ap-southeast-1.amazonaws.com/graphql",
    "aws_appsync_region": "ap-southeast-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-vftdh7stejc6lpqbh5dby6zaly",
    "aws_cognito_identity_pool_id": "ap-southeast-1:db01ba1b-c989-4331-ad78-6b788daa0e6a",
    "aws_cognito_region": "ap-southeast-1",
    "aws_user_pools_id": "ap-southeast-1_x6jmrc46x",
    "aws_user_pools_web_client_id": "64k4jgh1pgc75k2rb2md1meslv",
    "oauth": {}
};


export default awsmobile;
